### ISSUE TITLE
Zeilenumbrüche in Xml problematisch

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#120]
Wenn ein Id-Tag nicht in einer Zeile mit den Tags <Id></Id> steht, dann werden die Zeilenumbrüche Teil der Id. Das sollte nicht sein: Whitespaces sollten herausgefiltert werden. Das Gleiche gilt für die Elemente für Label und  Beschreibung. Hier werden z. B. beim Testheft Zeilenumbrüche generiert, so dass der Button zum Start des Testheftes größer wird.

**Comment by paflov** [comment]
z. B.
```
<Booklet>
<metadata>
<Id>
bla
</Id>
```
