### ISSUE TITLE
SysCheck: In CheckWorkspace einbeziehen, dass eine SysCheck-Xml eine ID enthalten muss.

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#128]
Vielleicht ein neuer Grund, die XSD-Schemadefinitionen zu singularisieren, d. h. die gemeinsame vo_Common.xsd aufzulösen und deren Definitionen (angepasst) in die anderen XSD zu übernehmen.

**Comment by paflov** [comment]
Dadurch, dass die ID inzwischen explizit in der XSD gefordert wird, ist das automatisch schon mit dabei:

```
[`syscheck2 (2).xml`] error reading SysCheck-XML-file `Error [1871] in line 4: Element 'Metadata': Missing child element(s). Expected is ( Id ).
```
