### ISSUE TITLE
PHPUnit updaten 

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter-backend#135]
phpunit/phpunit-mock-objects dependency entfernen

Wird nicht mehr gebraucht und ist außerdem als ungewartetes Fremdpaket unerwünscht.

**Comment by paflov** [comment]
Hmmm ich sehs gar nicht mehr in der aktuellen composer.json...

**Comment by rhenck** [comment]
Aber in der lock-Datei. Wird anscheinend von     "name": "phpunit/phpunit", "version": "6.5.14" benötigt.

**Comment by paflov** [comment]
Erfordert ein Update auf eine neuere Version von PHPUnit, Ticket umbenannt

https://stackoverflow.com/questions/55696556/how-to-fix-this-error-package-phpunit-phpunit-mock-objects-is-abandoned-you-sho
