### ISSUE TITLE
XSD Unit: Bei Metadaten wieder hinzufügen: Lastchange, Owner, Project

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#140]
Diese Infos werden durch die ItemDB in die Unit-XML reingeschrieben und führen im Moment zum Fehler.

**Comment by paflov** [comment]
Hm. wäre er sehr aufwendig stattdessen das Format bei der Item-DB anzupassen?

**Comment by mechtelm** [comment]
Es gibt jetzt schon sehr viele Units, die müssten alle neu erzeugt werden, wenn man nicht händisch alles rauslöschen will. Es geht nur darum, dass die XSD das erlaubt, nicht dass das Testcenter etwas damit macht.
