### ISSUE TITLE
Workspace-Check: Doppelter Login?

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#142]
Habe nur ein Testtaker-File und eine Testtaker-Gruppe und einen Login und bekomme Fehlermeldung 
"login `ego123` in `Logins MMe.XML` is already used in another file on this workspace"

**Comment by paflov** [comment]
Hm, das habe ich eigentlich neulich erst gefixed. Welche Instanz? iqb-testcenter.de?

**Comment by mechtelm** [comment]
itemdb2.iqb.hu-berlin.de

**Comment by paflov** [comment]
[wurde in 5.0.2 gefixed](https://github.com/iqb-berlin/testcenter-backend/commit/91c8eb9845c30720d604707fff7be1e73b29f00b#diff-8abc6d180b22598c919f162ed25a3449); auf dieser maschine läuft 5.0.1. Wird aber nicht mehr upgedatet denke ich.
