### ISSUE TITLE
initialize-php escapet Slashes in URLs nicht richtig

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter-backend#147]
# Fehlerbeschreibung

- Was ist passiert?
system.json sieht folgendermaßen aus:
{"broadcastServiceUriPush":"http:\/\/testcenter-broadcasting-service:3000","broadcastServiceUriSubscribe":"ws:\/\/localhost\/bs"}

- Was sollte passieren?
{"broadcastServiceUriPush":"http://testcenter-broadcasting-service:3000","broadcastServiceUriSubscribe":"ws://localhost/bs"}

- Call: Endpoint, Payload, Headers etc.
Hier der Aufruf in der entrypoint.sh
php /var/www/html/scripts/initialize.php \
  --user_name=$SUPERUSER_NAME \
  --user_password=$SUPERUSER_PASSWORD \
  --workspace=$WORKSPACE_NAME \
  --test_login_name=$TEST_LOGIN_NAME \
  --test_login_password=$TEST_LOGIN_PASSWORD \
  --test_person_codes="xxx yyy" \
  --broadcast_service_uri_push=$BROADCAST_SERVICE_URI_PUSH \
  --broadcast_service_uri_subscribe=$BROADCAST_SERVICE_URI_SUBSCRIBE

**Comment by paflov** [comment]
Scheint ja keine Probleme zu bereiten
