### ISSUE TITLE
Zeitpunkt abgleich irgendwo

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#162]
Die Clients haben manchmal eine falsche Zeit eingestellt (z. B. Windows 7 schlecht gepflegt oder paranoide Techniker). An irgendeiner Stelle sollte die Serverzeit mit einem Client-Zeitstempel weggespeichert werden, damit bei Bedarf eine sinnvolle Anzeige möglich ist.

**Comment by paflov** [comment]
Das betrifft wohl Log-Daten und Antworten. Es geht wohl darum, bei der Auswertung wiederum feststellen zu können, wann irgendetwas *wirklich* passierte, und nicht nur relativ zu einander. Beim Login werden ja Server-Seitige Zeitstempel verwendet, aber da kennt man wiederum die Client.Zeit nicht... ich werde mir zur gegebenen Zeit mal Gedanken machen.
