### ISSUE TITLE
Wiederverwertbare Logins (demo  / hot-restart modus): was passiert mit den alten logins?

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#163]
Wird bei einer Demo-Anmeldung das Token überschrieben oder ein neues erzeugt? In ersten Fall kann es also passieren, dass - wenn sich gleichzeitig zwei Personen mit den gleichen Zugangsdaten anmelden - die Authentifizierung verloren geht und der Ladevorgang scheitert (nach dem Laden gäbe es kein Problem mehr, da es keine Kommunikation mehr mit dem Server gibt). Im zweiten Fall stellt sich die Frage, wann alte Logins aufgeräumt werden. Die liegen ja eigentlich unbefristet herum.

**Comment by paflov** [comment]
Es wird ein neues erzeugt. Ich sehe da kein Problem, dass die in der Tabelle verbleiben, eine MySQL-Tabelle kann Problem Millionen von Zeilen verwalten. Grundsätzlich kann man aber auch über einen Aufräum-Prozess nachdenken. Das tangiert ja auch das Thema, das wir jüngst hatten: Logins/Personen löschen, die sich zwar eingeloggt haben, aber keinen Test gestartet haben und daher nicht gelöscht werden, wenn man die Ergebnisse löscht...

**Comment by paflov** [comment]
Kann dieses Ticket geschlossen werden?
