### ISSUE TITLE
Admin: Wird ggf. verhindert, dass Dateien gelöscht werden?

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#178]
Das Hochladen einer Booklet-Xml wird verhindert, wenn eine aufgerufene Unit-Xml nicht gefunden wird. Wenn man aber nachträglich diese Unit-Xml löscht, dann haben wir ja doch wieder Inkonsistenz. Sollte man das dann verhindern? Wird das aktuell verhindert?

**Comment by paflov** [comment]
Wird aktuell nicht verhindert. Sollte man aber machen! Kann ich mit überschaubarem Aufwand einbauen!
