### ISSUE TITLE
Kritischer Bug im Anmeldeprozess

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#179]
Rücksprache erforderlich

**Comment by paflov** [comment]
- prüfen ob getMemebers das selbe Problem hat
- prüfen warum dependency plötzlich nötig war

**Comment by paflov** [comment]
1) hatte es nicht gesondert, da vor der Anwendung das passwort schon gechecked wurde - wurde also mit-repariert. Aber, der $password-Parameter war hier unnötig und kam daher dass ich einst den Eindruck hatte, doppelte login.namen könnten erlaubt sein, wenn die Passwörter abweichen. Habe ihn entfernt und der Funktion einen (hoffentlich) sprechenderen Namen gegeben.

**Comment by paflov** [comment]
2. Konnte ich nicht reproduzieren. Habe is-promise rausgenommen, die tests laufen trotzdem. Lokal, und im Docker-Container. Werde ich erstmal ignorieren.
