### ISSUE TITLE
vo_SysCheck.xsd: Metadata verbessern

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#181]
Id und Label sollten Pflichteinträge sein.

**Comment by paflov** [comment]
Sofern ich das sehen kann, ist das bereits der Fall!?
Trag mal einen Verweis auf eine aktuelle XSD da ein, dann sollte die IDE dich warnen wenn ID oder LABEL fehlt.
```
<SysCheck xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter-backend/9.1.2/definitions/vo_SysCheck.xsd">
```

**Comment by mechtelm** [comment]
Richtig, default ist minOccurs="1"
