### ISSUE TITLE
SysCheck: Network-Test anders steuern

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#182]
... wenn DownloadSpeed/UploadSpeed nicht in der XML vorgegeben sind, d. h. es gibt keine Defaults. Dann dürften aber die Elemente nicht optional sein.

**Comment by paflov** [comment]
Die Defaults hast du rausgelöscht mein Lieber ;)
Vorschlag: Wenn keine Werte gegeben sind, dann entspricht das skipnetwork=true ?

**Comment by paflov** [comment]
Was hat das für eine Priorität?

**Comment by mechtelm** [comment]
Hm das Problem ist beim Schreiben der Doku aufgefallen, wo Normalos überfordert sind, Speed-Erwartungen zu formulieren. Aber dann wird in der Doku halt ein Beispiel gegeben, das muss reichen. Dann bleibt die skip-Option beim missing, das gefällt mir.

Dann müsste die xsd geändert werden (kein explizites `skipnetwork` mehr), und das FrontEnd muss entsprechend reagieren. Hm dann müsste man strenggenommen unterscheiden, ob upload UND download definiert ist oder nur eins von beidem.

**Comment by paflov** [comment]
Macht es denn Sinn nur Upload oder nur Download anzugeben? Ich würde sagen: nein.

**Comment by paflov** [comment]
Kann dieses Ticket geschlossen werden?
