### ISSUE TITLE
SysCheck: Bei Header-Element sollte der Value genommen werden und nicht der Prompt

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#183]

**Comment by paflov** [comment]
Hier müsstest du bitte etwas Erklärung hinzufügen :) Was bedeutet das für das Backend? Ist das nicht eine Frontend-Frage?

Ich hatte, nachdem Jenny davon verwirrt war, übrigens auch mal einen Vorschlag dazu gemacht:
[https://github.com/iqb-berlin/testcenter/issues/57](https://github.com/iqb-berlin/testcenter/issues/57)

**Comment by paflov** [comment]
Was hat das für eine Priorität?

**Comment by mechtelm** [comment]
Duplicate of iqb-berlin/testcenter#57
