### ISSUE TITLE
Upload Admin-Bereich: Reihenfolge modifizieren

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#188]
Wenn mehrere Dateien zum Upload ausgewählt werden oder eine ausgewählte Zip-Datei mehrere Dateien enthält, dann muss die Reihenfolge beim Einfügen in den Workspace separat bestimmt werden:
(1) Player,
(2) voud-Dateien der Units,
(3) Unit-Xmls,
(4) Booklet-Xmls und dann
(5) Testtakter-Xmls, ggf noch
(6) SysCheck-Xmls

**Comment by mechtelm** [comment]
Zeithorizont: Bis Ende Mai?

**Comment by mechtelm** [comment]
Ähm das ist vielleicht ein größeres Problem: Wenn man eine ZIP auspackt, dann kann man die Reihenfolge der Verarbeitung anschließend bestimmen. Sollten aber einfach 10 Dateien markiert werden zum Hochladen, dann sind das Einzelaktionen, deren Reihenfolge zufällig ist.

Die Lösung kann nur sein, dass man erst nach Abschluss aller Uploads (zwischenspeichern!) die Analyse und das Einfügen in den Arbeitsbereich anstößt. Das geht auch, weil das Frontend den Abschluss aller Uploads gemeldet bekommt und dann einen separaten Request für die Verarbeitung schicken kann.

Dasselbe Problem gibt es auch beim Import von Units in das Teststudio, da auch hier die Units meist aus zwei Dateien bestehen. Siehe Ticket iqb-berlin/teststudio-lite-setup#5

**Comment by paflov** [comment]
Gut, eigentlich sind das zwei Fälle:

**a) Zip-Archiv**
Reihenfolge recht leicht zu implementieren.

**b) Mehrere Dateien auf einmal (multipart) **
Der FileUploader des Frontends, den du gemacht hast erlaubt das zwar nicht. Chrome und andere Browser aber können das theoretisch aber (vllt FF inzwischen auch). Ich habe das schon beim Refactoring des Backends bedacht (das ja theoretisch auch andere Frontends kriegen kann) und das Backend kann damit umgehen und es wird nicht anders behandelt als die ZIP.

c) ** Mehrere Dateien werden auf vom User gleichzeitg gewählt, jedoch vom Uploader einzeln und asychron hochgeladen**
Das ist in der Tat komplizierter. Ich würde das lösen in dem ich beim Upload eine Information mitgebe wie viele Dateien gleichzeitig raufgezogen wurden und mit dieser Info im backend arbeite. Aber eigentlich finde ich das etwas unnötigen Aufwand und würde argumentieren wollen, dass man in diesem Fall halt die Reihenfolge einhalten muss.

**Comment by paflov** [comment]
Fall a) wurde abgedeckt, der Rest wie besprochen ausgelassen.
