### ISSUE TITLE
CustomText Konfiguration im Adminbereich

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/testcenter-backend#217]
# Fehlerbeschreibung

- beim Versuch CustomText Parameter im Adminbereich unter Einstellungen zu ändern, erscheint beim speichern der folgende Fehlercode: Allgemeines Serverproblem: failure response for https://www.iqb-testcenter.de/api/system/config/custom-text:500 Internal Server Error
- werden die Parameter via Testtakers.xml gesetzt funktioniert alles wie gewünscht

# Fehler-Kontext
- Version: 8.1.2 mit 11.5.7
- [Server](https://www.iqb-teststudio.de)

**Comment by paflov** [comment]
```SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'metaKey' at row 1```
