### ISSUE TITLE
CustomTexts für Logins wieder erlauben

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/testcenter-backend#227]
Der Enpunkt für die Person sieht zwar ein Objekt für die CustomTexts vor, das an das Frontend geschickt wird, das ist aber stets leer.

**Comment by paflov** [comment]
Kann ich nicht reproduzieren. Kannst du mal Beispieldateien anhängen oder so?

**Comment by mechtelm** [comment]
Kann ich auch nicht mehr reproduzieren, funktioniert korrekt.
